# Site settings
title: Mediachicken
email: self@mediachicken.com
description: > # this means to ignore newlines until "baseurl:"
  Self-taught jack of all trades. I dabble in everything from web
  development to game development. This is where
  I talk about it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mediachicken.com" # the base hostname & protocol for your site
twitter_username: igaret
github_username:  mediachicken

# Build settings
markdown: redcarpet

paginate: 10
paginate_path: "/:num/"

permalink: "/:title"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true
      related: true

gems:
  - jekyll-sitemap
  - jemoji
  - kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
